services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    privileged: true
    environment:
      JENKINS_OPTS: --prefix=/jenkins
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false -Djenkins.model.Jenkins.slaveAgentPort=50000"
      HOST_IP: ${HOST_IP}
      JENKINS_ADMIN_USER: ${JENKINS_ADMIN_USER}
      JENKINS_ADMIN_TOKEN: ${JENKINS_ADMIN_TOKEN}
      JENKINS_URL: "https://${HOST_IP}/jenkins"
    volumes:
      - home:/var/jenkins_home
      - ./config/jenkins/init:/var/jenkins_home/init.groovy.d
    networks:
      - jenkins_net
    healthcheck:
      test: ["CMD", "curl -k -s https://${HOST_IP}/jenkins/login"]
      interval: 5s
      timeout: 10s
      start_period: 5s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: jenkins-nginx
    restart: always
    depends_on:
      jenkins:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
      - "50000:50000"
    environment:
      - host_ip=${HOST_IP}
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.template:ro
      - ./config/nginx/nginx-entrypoint.sh:/docker-entrypoint.d/40-envsubst-nginx-config.sh:ro
      - ./config/nginx/certs:/etc/ssl/certs:ro
      - ./config/nginx/certs:/etc/ssl/private:ro
    networks:
      - jenkins_net
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://${HOST_IP}/jenkins/login"]
      interval: 30s
      timeout: 10s
      retries: 3

  agent1:
    image: jenkins-agent:latest
    container_name: agent1
    environment:
      - JENKINS_URL=https://${HOST_IP}/jenkins
      - JENKINS_AGENT_NAME=agent1
      - JENKINS_SECRET=${JENKINS_SECRET_AGENT1}
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    restart: always
    volumes:
      - agent1_workdir:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 30s
      timeout: 10s
      retries: 3

  agent2:
    image: jenkins-agent:latest
    container_name: agent2
    environment:
      - JENKINS_URL=https://${HOST_IP}/jenkins
      - JENKINS_AGENT_NAME=agent2
      - JENKINS_SECRET=${JENKINS_SECRET_AGENT2}
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    restart: always
    volumes:
      - agent2_workdir:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net
    healthcheck:
      test: ["CMD", "pgrep", "java"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  home:
  agent1_workdir:
  agent2_workdir:

networks:
  jenkins_net:
    driver: bridge